slogan: "欢喜就好~"

menu:
  - title: 归档
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: 目录
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: 标签
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: 关于我
    url: about
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: Freemind
    url: https://github.com/wzpan/freemind/
    intro: "Freemind's Github repository."
    icon: "fa fa-github"
  - title: "My Github"
    url: http://www.github.com/sunnogo
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "My LinkedIn"
    url: http://www.linkedin.com/in/sunyongfeng
    intro: "My Linkin account."
    icon: "fa fa-linkedin"

widgets:
- search
- category
- tagcloud
- recent_posts  
- links

rss: true
fancybox: true
favicon: favicon.png
duoshuo_shortname: sunnogo

# Analytics
google_analytics:
  enable: true
  siteid: UA-42535091-2
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR